### ISSUE TITLE
【小白求助】Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by DawnFaramita** [GamerNoTitle/bilibiliJudge#10]
![2323423423](https://user-images.githubusercontent.com/79857801/109909504-2f6b9e80-7ce1-11eb-9ac0-925cc6a04130.PNG)
![7655735754](https://user-images.githubusercontent.com/79857801/109909511-309ccb80-7ce1-11eb-9cb2-86515172bac4.PNG)

**Comment by GamerNoTitle** [comment]
emmmm 我这烂手机的邮件看不到图片 请发日志详细内容 谢谢

On Thu, 4 Mar 2021 12:01:09 +0800,  wrote:
> ![2323423423](https://user-images.githubusercontent.com/79857801/109909504-2f6b9e80-7ce1-11eb-9ac0-925cc6a04130.PNG)
> ![7655735754](https://user-images.githubusercontent.com/79857801/109909511-309ccb80-7ce1-11eb-9cb2-86515172bac4.PNG)
> 
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/GamerNoTitle/bilibiliJudge/issues/10
-- 
GamerNoTitle (\^3^/)
Sent by using BlackBerry 9720 LogicMail

**Comment by GamerNoTitle** [comment]
请参考这里https://github.com/GamerNoTitle/bilibiliJudge/blob/master/README.md#%E8%8E%B7%E5%8F%96%E6%A1%88%E4%BB%B6%E4%B8%80%E8%8A%82keyerror

**Comment by GamerNoTitle** [comment]
摸了会电脑才看到你发的图（＃v＃

**Comment by DawnFaramita** [comment]
> 摸了会电脑才看到你发的图（＃v＃

多谢大佬，搞定了
