### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by biliblihuorong** [GamerNoTitle/bilibiliJudge#16]
![image](https://user-images.githubusercontent.com/40906916/117757871-7fbc2b00-b253-11eb-9ea5-6b17c0e780ee.png)
参考了:https://github.com/GamerNoTitle/bilibiliJudge/blob/master/README.md#%E8%8E%B7%E5%8F%96%E6%A1%88%E4%BB%B6%E4%B8%80%E8%8A%82keyerror
但是号之后还是报错

**Comment by GamerNoTitle** [comment]
csrf无法校验，重新在网页登录后更新你的SESSDATA和CSRF2021年5月11日 12:22，biliblihuorong ***@***.***>写道：



参考了:https://github.com/GamerNoTitle/bilibiliJudge/blob/master/README.md#%E8%8E%B7%E5%8F%96%E6%A1%88%E4%BB%B6%E4%B8%80%E8%8A%82keyerror

但是号之后还是报错
