### ISSUE TITLE
目前每天只会执行1个案件的判定，不能自己判定每天要求的20个案子

### ISSUE THREAD

**Issue by Fitye** [GamerNoTitle/bilibiliJudge#2]
![1](https://user-images.githubusercontent.com/63393725/106381353-11193700-63f3-11eb-945a-c5686757ce28.png)

**Comment by ElainaMoe** [comment]
运行一次不是只判定一次呀 运行一次是判定到无法继续（例如：判定满20、B站案件库无新案件）

**Comment by GamerNoTitle** [comment]
有的时候当时运行的时候B站的案件库没有20个案件给你只给了你几个 这种情况可以选择多运行几次（自己改Judge.yml里面的cron，可以参考我楼上那个号）

如果是其他情况请描述清楚，谢谢

**Comment by Fitye** [comment]
> 有的时候当时运行的时候B站的案件库没有20个案件给你只给了你几个 这种情况可以选择多运行几次（自己改Judge.yml里面的cron，可以参考我楼上那个号）
> 
> 如果是其他情况请描述清楚，谢谢

主要是当我看到每天自动判定案子的时候，我看到他并没有自动下一个，当我手动点击下一个案子的时候也会正常出现，不是阿b没有给我案子，貌似是脚本没有进行下一个

**Comment by ElainaMoe** [comment]
https://github.com/GamerNoTitle/bilibiliJudge/blob/ccaf1a6fe94fc1e8aa86a570a25820e5d48cf644/GetNewCase.py#L15
把这个链接里面的15行在自己的仓库里面把#和后面的空格去掉，一定要保证print跟上下平齐
运行一下，看看结果

**Comment by ElainaMoe** [comment]
运行完给个反馈

**Comment by GamerNoTitle** [comment]
测完了吗

**Comment by GamerNoTitle** [comment]
![image](https://user-images.githubusercontent.com/28426291/106410677-56367b00-647e-11eb-9897-3757558b09f9.png)
nizhebush你这不是正常运行了吗

**Comment by Fitye** [comment]
> 测完了吗

更改完以后还是不行，默认只是判定一个案子

**Comment by Fitye** [comment]
> > 测完了吗
> 更改完以后还是不行，默认只是判定一个案子，可能系统分配的问题，我再去测试一下

**Comment by GamerNoTitle** [comment]
这就是案件库没有案件了呀 你看那行B站返回的输出
判不满20件建议在cron表达式中设置多几次 这个不是脚本问题
