### ISSUE TITLE
运行错误，求解

### ISSUE THREAD

**Issue by colorsakura** [GamerNoTitle/bilibiliJudge#3]
Run python3 Main.py "$scrf" "$sessdata" "$giveup" "$delay" "$JudgeProportion"
Traceback (most recent call last):
检测到放弃选项的开启状态为：是，判定比例为：70.0%，即将开始运行判定程序！
  File "Main.py", line 105, in <module>
    Main()
  File "Main.py", line 67, in Main
    Userinfo,UserinfoParsed=GetInfo(sessdata)
  File "/home/runner/work/bilibiliJudge/bilibiliJudge/GetJudgerInfo.py", line 18, in GetInfo
    '用户名': info_loads['data']['uname'][0]+ ('*' * int(len(info_loads['data']['uname'])-2)) +info_loads['data']['uname'][len(info_loads['data']['uname'])-1:],
KeyError: 'data'
Error: Process completed with exit code 1.

**Comment by GamerNoTitle** [comment]
找到GetJudgerInfo.py，在第12行下面加多一行
https://github.com/GamerNoTitle/bilibiliJudge/blob/621f07ca5ee024383252288983dab9f6169525e7/GetJudgerInfo.py#L12
改成
```python
    info_loads=js.loads(info.text)
    print(info_loads)
```
运行一次看看返回的是什么结果

**Comment by colorsakura** [comment]
{'code': -400, 'message': '请求错误', 'ttl': 1}

浏览器直接请求http://api.bilibili.com/x/credit/jury/jury返回正常
{"code":0,"message":"0","ttl":1,"data":{"caseTotal":12224,"face":"http://i1.hdslb.com/bfs/face/7f6907b34ad1a88989a425dfdf7d59465cc1bd49.jpg","restDays":30,"rightRadio":97,"status":1,"uname":"uname"}}

**Comment by GamerNoTitle** [comment]
换一下SESSDATA和csrf，重新登陆获取更新一下

**Comment by colorsakura** [comment]
没问题了。估计是csrf复制少了。
感谢

**Comment by GamerNoTitle** [comment]
好的 没有关系
