### ISSUE TITLE
在setting里填了必要参数 sessdata和csrf,运行的时候还是报必要参数缺失

### ISSUE THREAD

**Issue by cdlaimin** [GamerNoTitle/bilibiliJudge#5]
Run python3 Main.py "$scrf" "$sessdata" "$giveup" "$delay" "$JudgeProportion"
Traceback (most recent call last):
  File "Main.py", line 21, in <module>
    raise(VariableError('Essential variable(s) not available!'))
__main__.VariableError: Essential variable(s) not available!
必要变量未设置！程序即将退出！
Error: Process completed with exit code 1.

**Comment by GamerNoTitle** [comment]
@cdlaimin 贴一下当次运行的Action链接

**Comment by GamerNoTitle** [comment]
![image](https://user-images.githubusercontent.com/28426291/108591410-97e28380-73a3-11eb-9eff-b145b633b71f.png)

你csrf是空的，检查一下你的Secret里面的变量名字是否打对了吧
（刚好看到了我发现我变量名字打错了，不过打错不影响运行）
