### ISSUE TITLE
【疑似封脚本】风纪委员信息查询API请求被拦截

### ISSUE THREAD

**Issue by xhemj** [GamerNoTitle/bilibiliJudge#6]
错误信息：
```
File "Main.py", line 112, in <module>
    Main()
  File "Main.py", line 67, in Main
    Userinfo,UserinfoParsed=GetInfo(sessdata)
  File "/home/runner/work/bilibiliJudge/bilibiliJudge/GetJudgerInfo.py", line 18, in GetInfo
    '用户名': info_loads['data']['uname'][0]+ ('*' * int(len(info_loads['data']['uname'])-2)) +info_loads['data']['uname'][len(info_loads['data']['uname'])-1:],
TypeError: 'NoneType' object is not subscriptable
```

**Comment by GamerNoTitle** [comment]
看README的Q＆A那一节，然后运行一次贴结果

On Wed, 24 Feb 2021 18:56:09 +0800,  wrote:
> 地址：https://github.com/xhemj/bilibiliJudge/runs/1969379330?check_suite_focus=true

> 错误信息：

> ```

> File "Main.py", line 112, in <module>

>     Main()

>   File "Main.py", line 67, in Main

>     Userinfo,UserinfoParsed=GetInfo(sessdata)

>   File "/home/runner/work/bilibiliJudge/bilibiliJudge/GetJudgerInfo.py", line 18, in GetInfo

>     '用户名': info_loads['data']['uname'][0]+ ('*' * int(len(info_loads['data']['uname'])-2)) +info_loads['data']['uname'][len(info_loads['data']['uname'])-1:],

> TypeError: 'NoneType' object is not subscriptable

> ```

> 

> -- 

> You are receiving this because you are subscribed to this thread.

> Reply to this email directly or view it on GitHub:

> https://github.com/GamerNoTitle/bilibiliJudge/issues/6
-- 
GamerNoTitle (\^3^/)
Sent by using BlackBerry 9720 LogicMail

**Comment by xhemj** [comment]
```
{'code': -412, 'message': '请求被拦截', 'ttl': 1, 'data': None}
```

**Comment by GamerNoTitle** [comment]
可能B站开始封脚本了，我回去再看看其他的API能不能用，最好的情况是只有信息获取不能用，其他照常运行；最坏的情况是大部分API都不接受来自Github的请求，那我就要看看能不能转战云函数了

顺带一提：我周五下午回去

On Wed, 24 Feb 2021 21:16:19 +0800,  wrote:
> ```

> {'code': -412, 'message': '请求被拦截', 'ttl': 1, 'data': None}

> ```

> 

> -- 

> You are receiving this because you commented.

> Reply to this email directly or view it on GitHub:

> https://github.com/GamerNoTitle/bilibiliJudge/issues/6#issuecomment-785067092
-- 
GamerNoTitle (\^3^/)
Sent by using BlackBerry 9720 LogicMail

**Comment by luoxuebinfei** [comment]
B站检查请求头了，在GetJudgerInfo.py文件中headers应改为
headers={
        'cookie': test,
        'Host': 'api.bilibili.com',
        'User-Agent': UserAgent().random,
    }
即可通过验证

**Comment by ElainaMoe** [comment]
> B站检查请求头了，在GetJudgerInfo.py文件中headers应改为
> headers={
> 'cookie': test,
> 'Host': 'api.bilibili.com',
> 'User-Agent': UserAgent().random,
> }
> 导入模块要加上from fake_useragent import UserAgent
> 即可通过验证

这个cookie应该还是只需要SESSDATA吧
我周五回去改，感谢(\*^_^\*)

**Comment by luoxuebinfei** [comment]
> > B站检查请求头了，在GetJudgerInfo.py文件中headers应改为
> > headers = { 
> > 'cookie'：test，
> > 'Host'：'api.bilibili.com'，
> > 'User-Agent'：UserAgent（）。random，
> > }
> > 引入模块要加上来自fake_useragent import UserAgent
> > 就可以通过验证
> 
> 这个Cookie应该还是只需要SESSDATA吧
> 我星期五回去改，感谢（* ^ _ ^ *）

嗯。cookie没变，就是要加上host和user-agent，但估计B站之后可能会加大对脚本的查封了

**Comment by GamerNoTitle** [comment]
稍微摸了一下 已经合并到了[我的小号](https://github.com/ElainaMoe/bilibiliJudge)
先试试运行几天看看结果吧
如果你也想帮我测试一下的话就用下面的这条链接新建PR
https://github.com/你的用户名/bilibiliJudge/compare/master...GamerNoTitle:AntiScriptFix

运行几天没问题了我会合并到master分支的

**Comment by ElainaMoe** [comment]
已经将更改合并入主分支 更新脚本后即可正常运行
